src/moltin.coffee
User reporting bug missing modifier creation and reported fix.
=> Addition of modifier creation in node-sdk.

src/moltin.coffee
Could you please have a look when you got a chance @jHoldroyd 
Fix https://github.com/moltin/js-sdk/issues/29
=> Store access token details preserving format

src/config.js, src/factories/request.js
Adds some headers to track SDK language and versions
=> SDK tracking

Jenkinsfile
DO NOT MERGE! :
I need first to figure out what's happening with Jenkins and when happy 😄 we can merge 
---
**UPDATE:**
Ready to 🚀
=> chore: remove trailing newline when echoing the npm token + refactor

rollup/cjs.config.js, rollup/umd.config.js, src/factories/request.js
Make sure we roll all external dependencies into the bundle.
=> fix: Fix the UMD bundle

Jenkinsfile
=> build: Reinstate additional npm install step

src/config.js, src/factories/request.js
=> feat: Adding new header field for application tracking

.babelrc, .eslintrc.yml, package.json, test/factories.js, test/unit/authentication.js, test/unit/brands.js, test/unit/cart.js, test/unit/categories.js, test/unit/collections.js, test/unit/currencies.js, test/unit/gateways.js, test/unit/orders.js, test/unit/products.js
Refactor test suite to use ES6 modules, rather than compiled CJS bundle.
=> test: Test against ES6 modules

src/endpoints/orders.js, test/factories.js, test/unit/orders.js
Adds a `Transaction` method to the `Orders` class to fetch a all transactions from an order.
```js
Moltin.Orders.Transactions(id);
```
=> feat: Add method to GET all transactions on an order

.github/PULL_REQUEST_TEMPLATE.md
A nice formatted PR template ready for any contributions.
=> chore: Adding a PR template

src/endpoints/customers.js, test/factories.js, test/unit/customers.js, test/unit/gateways.js
* ✅ Ready
* ### Feature
* [FEAT] Add `Token` method to retrieve [JWT](https://jwt.io) for store customers
* N/A
* Fixes moltin/workflow#2696
* N/A
=> feat: Customer tokens

src/endpoints/orders.js, src/extends/base.js, src/factories/request.js, test/unit/authentication.js, test/unit/brands.js, test/unit/cart.js, test/unit/categories.js, test/unit/collections.js, test/unit/currencies.js, test/unit/customers.js, test/unit/gateways.js, test/unit/orders.js, test/unit/products.js
* ✅ Ready
* ### Feature
* [FEAT] Adds optional `token` parameter to `All()` method. Can be used to retrieve orders tied to a specific customer
* N/A
* N/A
Use in conjunction with `Token()` method to retrieve all orders tied to a specific customer.
```js
async getCustomerOrders() {
// Get a customer token 
const customer = await Moltin.Customers.Token('jonathan@moltin.com', 'password');
// Use token in request header to get orders tied to customer
await Moltin.Orders.All(customer.token);
}
=> feat: Token paremeter to GET customer orders

src/endpoints/cart.js, src/utils/helpers.js, test/unit/cart.js, test/utils/helpers.js
* ✅ Ready
* ### Feature
* [FEAT] Adds functionality to add a promotion to a cart
* N/A
* N/A
* N/A
=> feat: Cart promotion item

.eslintrc.yml, src/endpoints/cart.js, src/moltin.js, src/utils/helpers.js, test/unit/cart.js
* ⛔ Hold
* ### Refactor
* [REFACTOR] Expose a Cart method on the Moltin class
* [REFACTOR] Checkout method refactored to accept multiple parameters: customer, billing, shipping 
* N/A
* N/A
* Don't merge, for now.
=> refactor: Cart checkout method

README.md
* ✅ Ready
* ### Docs
* [DOCS] Removing reference to now removed repository wiki
* N/A
* N/A
* N/A
=> docs: Removing reference to wiki

src/endpoints/customers.js, test/unit/customers.js
* ✅ Ready
* ### Fix
Fixes a bug
* [FIX] Add `type` to customer token payload. This is now expected by the API
* N/A
* N/A
* Will need to subsequently bring this patch to the `2.x.x` releases too
=> fix: Add type to customer token payload

src/extends/base.js, test/unit/customers.js, test/unit/orders.js
* ✅ Ready
* ### Feature
Implements a new feature 
* [FEAT] Adds JWT token parameter to `Get` method so individual orders, customers can be fetched with `implicit` authentication
* N/A
* N/A
* N/A
=> feat: Add JWT parameter to Get method

src/extends/base.js, src/extends/catalogue.js, test/unit/orders.js
* ✅ Ready
* ### Feature
* [FEAT] Add `With()` method to the base class. This allows for all classes to use `includes` query parameter. `Moltin.Orders.With('items').All()`
* N/A
* N/A
* N/A
=> feat: Add With() method base class

src/endpoints/products.js, src/extends/base.js, test/unit/customers.js, test/utils/helpers.js
* ✅ Ready
* ### Feature
* [FEAT] Add `Filter()` method to the base class. This allows for all classes to use `filter` query parameter (i.e. `Moltin.Customers.Filter({ eq: { email: 'jonathan@moltin.com' } }).All()`).
* N/A
* N/A
* N/A
=> feat: Filter method base class

src/endpoints/inventories.js, src/moltin.js, test/factories.js, test/unit/inventories.js
* ✅ READY
Implements CRUD operations for Inventory
Implements Inventory support for;
- Get stock for all products
- Get the stock for a product
- Get stock transactions for a product
- Create a stock transaction for a product (increment/decrement)
None
None
None
=> feat: Add support for Inventory

rollup.config.js
* ✅ Ready
* ### Fix
Fixes a bug
* [FIX] Mark `cuid` as an external dependency to fix bundle configuration
* N/A
* N/A 
* Technically *not*  a commit that would normally require a bump. However the bundles are broken in this instance we can make an exception 🚨
=> fix: Declare CUID an external dependency

src/endpoints/orders.js, test/unit/orders.js
* ✅ Ready
* ### Feature
* [FEAT] Add `Update()` method to orders class
* https://github.com/moltin/api-reference/pull/117
* N/A
* N/A
=> feat: Order update functionality

package.json, src/endpoints/addresses.js, src/moltin.js, test/factories.js, test/tests.js, test/unit/addresses.js
* ✅ Ready
* ### Feature
* [FEAT] Adds CRUD functionality for addresses
* N/A
* Fixes https://github.com/moltin/workflow/issues/2969
* N/A
=> feat: Customer addresses

.eslintrc.json, src/utils/helpers.js, test/unit/products.js, test/utils/helpers.js
* ✅ Ready
* ### Fix
Fixes a bug 
* [FIX] Don't wrap sort query param value in parentheses
* N/A
* Fixes #148 
* N/A
=> fix: Sort query params

rollup.config.js
* ✅ Ready
* ### Fix
Fixes a bug
Fixes broken `umd` build as reported by @Jmz 
Closes https://github.com/moltin/workflow/issues/3167
=> fix: Remove cuid as a external rollup dep

README.md
* ✅ Ready
* ### Docs
Updates README docs for running rollup in development.
PS. Branch named `chore`  🙈
=> docs: Update README wording

.eslintrc.json, package-lock.json, package.json, src/utils/helpers.js
* ✅ Ready
* ### Fix
Fixes a bug
Removes the `cuid` dep in replacement of a random string generator.
* Closes https://github.com/moltin/js-sdk/issues/150
=> Fix: CJS import

.eslintrc.json, src/factories/request.js, src/factories/storage.js
* ✅ Ready
* ### Fix
Fixes a bug
* [FIX] Fixes an issue where credentials are not available to request after initial auth
* N/A
* Fixes #150 
* N/A
=> fix: Request credentials params

.gitignore, src/endpoints/orders.js, src/endpoints/transactions.js, src/moltin.js, test/tests.js, test/unit/orders.js, test/unit/transactions.js
* ✅ READY
* ### Feature
This PR adds order transactions support.
Requires tests. On hold.
=> feat: Add order transactions

src/utils/helpers.js, test/utils/helpers.js
* ✅ Ready
* ### Feature
* [FEAT] Enable related resource filtering via SDK `Filter()` method.
```js
Moltin.Products.Filter({ eq: { brand: { id: '123' } }).All()
```
* N/A
* N/A
This will also support feature API expansion to the functionality, such as additional filter attributes and operators.
```js
Moltin.Products.Filter({ like: { category: { slug: 'summer-*' } }).All()
```
=> feat: Related resource filtering

src/endpoints/files.js, src/moltin.js, test/unit/files.js
* ✅ Ready
* ### Feature
* [FEAT] Add Files class for `Get()`, `All()` methods
* N/A
* N/A
* Just read endpoints, not write.
=> feat: Files class

README.md
* ✅ Ready
* ### Docs
Update API ref link
=> docs: Update API ref link in README

renovate.json
* ✅ Ready
* ### Chore
This adds for now myself, @ynnoj and @craigtweedy as default reviewers for new PRs by renovate.
=> chore: Add default suggested reviewers

package-lock.json
* ✅ Ready
* ### Chore
Update pkg lock
=> chore(deps): update pkg lock

examples/index.html
* ✅ Ready
* ### Chore
Fixes an incorrect umd include during development.
=> chore: update umd path for dev example

src/moltin.d.ts
* ✅ Ready
* ### Fix
Fixes a bug
* [FIX] Add type definitions for jobs class
* N/A
* N/A
* N/A
=> fix: Add type definitions for jobs class

package-lock.json, src/endpoints/cart.js, src/moltin.d.ts, test/unit/cart.js
* ✅ Ready
* ### Feature
Implements a new feature 
This feature makes it possible to enrich the `Cart UpdateItemQuantity` endpoint with additional Flow data. This is currently supported by the API but not reflected in the documentation or in the SDK.
The name of the method `UpdateItemQuantity` seems to narrow. We should consider renaming it to a more general name.
`UpdateItem` sounds accurate.
=> feat: Allow sending flow data when updating cart items

src/endpoints/cart.js, src/moltin.d.ts, test/unit/cart.js
* ✅ Ready
* ### Feature
Adds support for the additional tax endpoints on a cart, as well as extending cart item functionality to allow includes, which allows developers to get additional information about taxes in their cart.
=> feat: add support for taxes

package-lock.json
* ✅ Ready
* ### Chore
* [CHORE] Fix dependency vulnerabilities
* N/A
* N/A
* N/A
=> chore: Fix dependency vulnerabilities

src/factories/request.js
* ### Fix
Fixes a bug  
* [FIX] Adds `X-MOLTIN-SDK-LANGUAGE` header to auth requests
* N/A
* N/A
* N/A
=> fix: Adds X-MOLTIN-SDK-LANGUAGE header to auth

.github/PULL_REQUEST_TEMPLATE.md
* ### Docs
* [DOCS] Remove status field from PR template
* N/A
* N/A
* Create a `draft` PR if still a WIP or on hold 👍
=> docs: Remove status field from PR template

src/utils/helpers.js, test/factories.js, test/unit/error.js
* ### Fix
Fixes a bug
* [FIX] Ensure we surface full error responses to the client
* N/A
* Fixes #250 
* N/A
=> fix: Return full error response

src/extends/crud.js, test/unit/customers.js
* ### Feature
* [FEAT] Add `token` parameter to `Update` method, which can be used to update a customer record implicitly
* N/A
* Fixes #251 
* N/A
=> feat: Add token parameter to update method

renovate.json
=> chore: remove tweedy from reviewers

src/endpoints/files.js, test/unit/files.js
* ### Feature
Adds the ability to delete a file by ID.
Closes #259
=> feat: handle file delete

renovate.json
* ### Chore
* Run renovate weekly
* Remove reviewers
=> chore(config): run renovate weekly

.circleci/config.yml
* ### Feature
* ### Fix
- fix: Update node dependency for Circle CI
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Update node dependency for Circle CI

README.md
* ### Docs
Need to update documentation for JS-SDK to explicitly call out definitions that developers need to create when adding support for flows:
[MT-2969](https://elasticpath.atlassian.net/browse/MT-2969)
=> docs:updated readme with typesript support

package.json, src/types/cart.d.ts, test/unit/cart.ts
* ### Fix
This PR is fixing type definitions for Cart and CartItem types. Tests were also updated to check for TypeScript properties for these types. Closes #342 .
=> Fixed response types for Cart and CartItem

src/endpoints/cart.js, src/types/cart.d.ts, test/unit/cart.ts
* ### Feature
Add `getCartsList` method and `createCart` method
=> feat: Added methods for create a cart and get carts list

package.json, src/endpoints/cart.js, src/types/cart.d.ts, src/utils/helpers.js, test/unit/cart.ts
* ### Feature
* ### Style
Add support for bulk update of cart items
* Fixes # [MT-4093]
A bunch of prettier updates too, have added prettier to the `lint-staged` config to avoid in future
[MT-4093]: https://elasticpath.atlassian.net/browse/MT-4093
=> feat: add bulk update for cart items

src/endpoints/authentication-settings.js, test/unit/authentication-settings.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> External authentication addon customer authentication settings: moved customer-authentication-settings under v2/settings

src/endpoints/promotions.js, src/moltin.d.ts, src/moltin.js, src/types/promotions.d.ts, test/factories.ts, test/tests.ts, test/unit/accounts.ts, test/unit/promotions.ts
* ### Feature
Added CRUD for promotions 
Also added CRUD for promotions codes and promotions attributes endpoint
Code for testing:
```
const authenticate = () => {
const body = {
grant_type: 'password',
username: '',
password: '',
client_id: '',
client_secret: ''
}
return fetch('https://api.moltin.com/oauth/access_token', {
method: 'POST',
headers: {
'Content-Type': 'application/x-www-form-urlencoded'
},
body: Object.keys(body)
.map(k => `${encodeURIComponent(k)}=${encodeURIComponent(body[k])}`)
.join('&')
}).then(res => res.json())
}
const Moltin = moltin.gateway({
custom_authenticator: authenticate
})
Moltin.Authenticate().then(res => {
Moltin.Accounts.Stores().then(({ data }) => {
Moltin.Accounts.SwitchStore(data[1].id).then(() => { …
```
=> Feat: added promotions and promotion codes endpoints

src/endpoints/oidc-profile.js, src/moltin.d.ts, src/moltin.js, src/types/oidc-profile.d.ts, test/unit/oidc-profile.ts
* ### Refactor
this pr updates the sdk to reflect recent renamings of profiles to oidc-profiles in the backend
N/A
N/A
N/A
=> [MT-1269] Update authentication profile -> oidc profile based on backend changes

src/endpoints/cart.js, src/types/cart.d.ts, test/unit/cart.ts
* ### Feature
- Added missing call to Update a Tax Item
- Added more documentation to cart endpoint
=> Feat: added endpoint for tax item update, added docs for cart endpoints

src/endpoints/flows.js, src/types/flow.d.ts, test/unit/flows.ts
* ### Feature
Added entry relationships endpoints
https://documentation.elasticpath.com/commerce-cloud/docs/api/advanced/custom-data/entry-relationships.html
=> Feat: added flows entry relationships endpoints

src/endpoints/cart.js, src/types/cart.d.ts, test/unit/cart.ts
* ### Feature
Added endpoint for update cart data
=> feat: added endpoint for update cart data

src/endpoints/inventories.js, src/types/inventory.d.ts
* ### Feature
Add docs for inventory endpoints.
* ### Fix
Remove duplicate Get function for inventories
=> feat: Add docs for inventory endpoints. Remove duplicate Get function

src/types/settings.d.ts
=> docs: updates settings endpoint documentation

src/endpoints/orders.js, src/endpoints/transactions.js, src/types/order.d.ts, src/types/transaction.d.ts, test/unit/orders.ts, test/unit/transactions.ts
* ### Feature
* Added get a single Transaction
* Added confirm Transaction
* Added more documentation to order and transaction endpoints
=> feat: Added Transactions operations

src/endpoints/products.js, src/endpoints/variations.js, src/moltin.d.ts, src/moltin.js, src/types/flow.d.ts, src/types/product.d.ts, src/types/variations.d.ts, test/factories.ts, test/tests.ts, test/unit/products.ts, test/unit/variations.ts
* ### Feature
Added variation endpoints
https://elasticpath.atlassian.net/browse/MT-3380
=> feat: added variations endpoint

src/endpoints/cart.js, src/types/cart.d.ts, test/unit/cart.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test:
Add Test for removeAllItems
* ### Chore
Add Endpoint for remove all items from cart (Make cart empty), Add test and type.
* Fixes #
=> feat: remove all items from cart

src/config.js, src/factories/request.js, src/types/config.d.ts
* ### Feature
Added ability to set custom headers
=> feat: added ability to set custom headers

src/types/order.d.ts
* ### Fix
Fixes order update response type, the response should be a resource
=> fix: order update response type

src/moltin.js
Updated cart object to create the Cart() function when cartId does not exists
=> fix: null cart object on storefront

package.json, src/endpoints/cart.js, src/types/cart.d.ts
Update to add options to BulkAdd for cart
=> feat: options to bulk update cart

src/types/order.d.ts
* ###  Fix
Updated order relationship items type
=> fix: order relationship items type

src/endpoints/accounts.js, src/factories/request.js, src/types/accounts.d.ts, test/unit/accounts.ts
* ### Feature
Implements an endpoint for adding a user to store
=> feat: endpoint for adding a user to store

src/types/order.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
Add "created_at" to the orders filter, to use it in re-order component.
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=>  feat: Add "created_at" to the orders filter 

src/moltin.d.ts, src/types/gateway.d.ts
* ### Feature
add types for gateway
add types for gateway
=> feat: add types for gateway

src/types/authentication-realm.d.ts, src/types/authentication-settings.d.ts, src/types/product.d.ts
* ### Fix
- Added id to settings type
* ### Docs
- Added missing docs for auth settings and auth realms
- Added missing docs for product
=> fix: auth settings type, added docs

src/types/authentication-realm.d.ts
* ### Fix
- added redirect_uris param to realm body type 
- updated realms CRUD docs
=> fix: added redirect_uris param, updated realms CRUD docs

src/types/cart.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
change type of carts endpoint based on queryableResource to get the Offset and Limit.
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=>  change type of carts endpoint based on queryableResource

src/endpoints/authentication-realm.js, src/types/authentication-realm.d.ts
* ### Fix
Realms update function 
Realms update function didn't allow to send a type and did not add it by itself (as in other endpoints) so all requests always failed for me
=> fix: realms update endpoint

src/types/core.d.ts
* ### Fix
Added validation field for Attribute
=> fix: Add validation field for Attribute

src/endpoints/cart.js, src/types/cart.d.ts, src/utils/helpers.js, test/unit/cart.ts, test/utils/helpers.ts
AddProduct By SKU
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
Test added to check AddProduct by SKU
* ### Chore
Add `isSku` to buildCartItemData, to add product by SKU number.
* Fixes #
=> feat : AddProduct By SKU 

src/types/oidc-profile.d.ts
* ### Fix
Fixed  OpenID profile endpoint types added docs links
=> fix: updated OpenID profile endpoint types

.github/workflows/main.yml
- Attempt fix CircleCI PR builds
* ### Fix
- Attempt fix CircleCI PR builds
=> fix: fix CircleCI PR builds

src/types/product.d.ts
* ### Feature
Add `Children` relationships to product relations
* Fixes #
=> feat:  update products relations

src/types/cart.d.ts
* ### Feature
Cart expiry date 
Add `expires-date` to cart timestamp
=> feat: cart expires date

src/types/cart.d.ts
* ### Fix
Fixes a bug
- Revert cart expires date
=> fix(): Revert cart expires date

package.json
* ### Feature
- Update node-localstorage to latest
=> feat: Update node-localstorage

src/endpoints/accounts.js, test/unit/accounts.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-6385] Removed commented out code

src/types/pcm.d.ts
* ### Fix
fix pcm product type
fix pcm product type
=> fix: pcm type

src/types/catalogs.d.ts
make optional created_at and updated_at
=> fix: catalog type

src/endpoints/jobs.js, src/types/job.d.ts, test/unit/jobs.ts
Update jobs types and Add `All()` endpoint to jobs endpoints
=> feat: Update jobs 

src/moltin.d.ts, src/moltin.js, src/types/file.d.ts
* ### Feature
Credential exposed through function
* ### Fix
Fixed file type
Need credential for file upload outside SDK
=> feat: credential exposed through function, fixed file type

src/endpoints/account-authentication-settings.js, src/moltin.d.ts, src/moltin.js, src/types/account-authentication-settings.d.ts, test/tests.ts, test/unit/account-authentication-settings.ts
* ### Feature
get account authentication setting endpoint is added
=> [MT-6387] Account Auth Setting for Account Management

src/endpoints/transactions.js, src/types/transaction.d.ts
* ### Feature
Update Refund endpoint
=> feta: Update Refund endpoint

src/types/transaction.d.ts
* ### Fix
Added missed props in Transaction Base
=> fix: Added missed props in Transaction Base

src/endpoints/account-members.js, src/moltin.d.ts, src/moltin.js, src/types/account-members.d.ts, test/unit/account-members.ts
* ### Feature
List Account Members API is added
List Account Members API is added. The js sdk is added for this api.
=> [MT-6487] Get Account Members

src/types/order.d.ts
update types of `created_at` and `updated_at` in order filters type
update types of `created_at` and `updated_at` in order filters type
=> feat: update types of Dates in order type

src/types/order.d.ts
Update type of customers name and email in orders types
=> feat: orderfilters type

src/endpoints/accounts.js, src/moltin.d.ts, src/moltin.js, test/unit/accounts.ts
* ### Feature
adds the Accounts.All() function to list accounts
also renamed Account to Accounts for consistency
n/a
MT-6474
n/a
=> [MT-6474] Add Accounts list

src/endpoints/node-relationships.js, src/types/node-relationships.d.ts
* ### Feature
Added  create parent node endpoint `/experimental/hierarchies/{id}/nodes/{nodeID}/relationships/parent`
Need it  for https://elasticpath.atlassian.net/browse/PM-3010
=> feat: added create parent node endpoint

src/moltin.d.ts
* ### Fix
Added missing node relationships types export
=> fix: node relationships type export

src/types/field.d.ts
* ### Fix
Fixes Field  interface
=> fix: Field relationship types fixed

src/types/price-books.d.ts
* ### Feature
updated pricebook types
updated pricebook types
=> feat: updated pricebook types

src/endpoints/price-book-prices.js, src/moltin.d.ts, src/types/price-book-prices.d.ts, src/types/price-books.d.ts
* ### Fix
Updates PriceBookPriceBase interface according to the latest API changes, adds export of prices types
=> fix: prices endpoint

src/types/price-books.d.ts
* ### Feature
Updated PriceBookSort type
=> feat: Update PriceBookSort type

src/endpoints/catalogs.js, src/endpoints/node-relationships.js, src/types/catalogs-nodes.d.ts, src/types/catalogs-products.d.ts, src/types/catalogs-releases.d.ts, src/types/catalogs.d.ts, src/types/node-relationships.d.ts
* ### Feature
Updates catalogs endpoints
* ### Fix
Removes non-existent endpoint
=> feat: update catalogs endpoints

src/endpoints/price-book-prices.js, src/types/price-book-prices.d.ts, src/types/price-books.d.ts
* ### Fix
Fixed types for pricebooks & product prices endpoints
=> fix: fixed types for pricebooks & prices

src/endpoints/account-memberships.js, src/types/account-memberships.d.ts, test/factories.ts, test/unit/account-memberships.ts
* ### Feature
adds account-memberships list capability
https://gitlab.elasticpath.com/commerce-cloud/account-management.svc/-/merge_requests/92
MT-6765
* Fixes #
n/a
=> [MT-6765] Add account-memberships list

src/types/account-authentication-settings.d.ts, src/types/account-memberships.d.ts, test/factories.ts, test/unit/account-memberships.ts
* ### Refactor
instead of - we want to use _ for all types in AM
=> [MT-7253] use _ instead of - in AM types

src/utils/helpers.js
* ### Feature
Add explicit logging to trace token validation bugs
=> feat: add explicit logging to token validation to track down errors

src/types/accounts.d.ts, test/unit/accounts.ts
* ### Fix
Fixes a bug
* ### Docs
* Removes the address field from accounts
=> [MT-7306] Remove Company Address from Account

src/endpoints/merchant-realm-mappings.js, src/moltin.d.ts, src/moltin.js, src/types/authentication-realm.d.ts, src/types/merchant-realm-mappings.d.ts
* ### Feature
Added merchant realm mappings endpoints
https://elasticpath.atlassian.net/browse/MT-6773
=> feat: merchant realm mappings

src/types/merchant-realm-mappings.d.ts
* ### Fix
unused text
Ci kickstart
=> fix: unused text

src/endpoints/catalogs.js
* ### Fix
Update Catalogs endpoints
=> fix: Update Catalogs endpoints

src/endpoints/nodes.js, src/types/nodes.d.ts
* ### Feature
Implements node's children endpoint
=> feat: adds node children endpoint

src/types/nodes.d.ts
* ### Fix
Node types
Added parent relationships
=> fix: node types

src/types/nodes.d.ts
=> fix: ci trigger

src/types/node-relationships.d.ts, src/types/nodes.d.ts
* ### Fix
node relationships product type
=> fix: node relationships product type

src/endpoints/node-relationships.js, src/types/node-relationships.d.ts
* ### Fix
Pagination added 
https://elasticpath.atlassian.net/browse/MT-7065
=> fix: node product pagination

src/endpoints/price-book-prices.js, src/types/price-book-prices.d.ts
* ### Feature
Added Prices filter
=> feat: Prices filter

src/types/authentication-realm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-3249] Added duplicate_email_policy to Realms

src/endpoints/price-book-prices.js
* ### Fix
Fixes all prices endpoint
=> fix: all prices endpoint

src/endpoints/pcm-file-relationship.js, src/endpoints/pcm.js, src/moltin.d.ts, src/types/pcm-file-relationship.ts, src/types/pcm.d.ts
* ### Feature
Implements pcm product file relationships
pcm product file relationships
=> feat: pcm product file relationships

src/types/nodes.d.ts
* ### Fix
Update NodeBase type
=> fix: Update NodeBase type

src/endpoints/heirarchies.js, src/types/hierarchies.d.ts
* ### Fix
Fixes hierarchy node filters
=> fix: hierarchy node filters

src/endpoints/node-relationships.js, src/types/node-relationships.d.ts
* ### Feature
Implements an endpoint to delete node parent
=> feat: delete node parent

src/types/order.d.ts
* ### Fix
Fixed order sorting an relationship types 
https://elasticpath.atlassian.net/browse/MT-8242
=> fix: order types

src/types/promotions.d.ts
New promotion type
* ### Feature
Free Gift (bundle gift) promotion
Add new promotion types, Free gift.
=> feat: Add bundle gift Schema and promotion type

src/endpoints/accounts.js, src/types/accounts.d.ts
* ### Fix
Fixes a bug
This change how data is being sent to the server when new account is being created. It also fixes a signature for `Create()` method
=> fix: Fixed signature for creating Accounts

src/types/accounts.d.ts
* ### Fix
Fixes a bug
Adding `registration_id` field to `AccountBase` so it can be fetched and updated.
=> fix: Added registration_id field to AccountBase

src/types/price-book-prices.d.ts
* ### Feature
Updates price interface
https://elasticpath.atlassian.net/browse/MT-8576
=> feat: sale prices

src/types/pcm-file-relationship.ts, src/utils/helpers.js
* ### Feature
Added support for files meta. tags product relationship
Needed for https://elasticpath.atlassian.net/browse/MT-7125
=> feat: added support for files meta. tags relationship

src/endpoints/accounts.js
* ### Fix
Removed custom account get signature that wasn't in sync with the type definition.
=> fix(Account get): Removed custom account get signature

src/endpoints/accounts.js
* ### Fix
Removed redundant update overload for accounts
=> fix(Removed redundant update overload):

src/endpoints/flows.js, src/types/flow.d.ts
* ### Feature
Templates
Add templates endpoints and types
https://elasticpath.atlassian.net/browse/MT-8187
https://elasticpath.atlassian.net/browse/MT-7983
=> feat: Add templates endpoint and types

src/types/authentication-realm.d.ts, src/types/oidc-profile.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> Realms fixed

src/endpoints/account-addresses.js
=> fix: accounts addresses

src/types/order.d.ts
update orders filter: add account_id
=> feat: update orders filter: add account_id

src/endpoints/account-addresses.js, src/endpoints/account-memberships.js, src/types/account-address.d.ts, src/types/account-memberships.d.ts, src/types/core.d.ts
* ### Fix
account addresses get list
business accounts memberships included type
https://elasticpath.atlassian.net/browse/MT-9179
=> fix: business accounts memberships included type

src/types/price-book-prices.d.ts
* ### Feature
Add tiers  types to PriceBookPriceBase
=> feat: Add tiers types to PriceBookPriceBase

src/types/promotions.d.ts
new promotion attribute
* ### Feature
Add Quantity limit per use type to promotions body
=> feat: Quantity limit per use

playground/index.ts, src/endpoints/accounts.js, src/types/accounts.d.ts, test/unit/accounts.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-6967] Filter for accounts

playground/index.ts, src/endpoints/account-members.js, src/types/account-members.d.ts, test/unit/account-members.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-6768] Filtering on /v2/account-members

src/types/customer.d.ts, test/unit/customers.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-9073] Customers. API GET customer should support partial match filtering

src/types/promotions.d.ts
* ### Feature
Adds a new field to PromotionCode interface: consume_unit
https://elasticpath.atlassian.net/browse/MT-9346
=> feat: consume_unit field added to PromotionCode object

src/endpoints/promotions.js, src/types/promotions.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: add limit, offset to codes endpoint

src/types/promotions.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: add all to itempercentdiscount types

src/endpoints/account-members.js
=> fix: account members endpoint

src/endpoints/catalogs.js, src/types/catalogs-products.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add products filter

src/endpoints/inventories.js, src/types/inventory.d.ts
* ### Feature
inventory service update, added new endpoints + types update
MT-9742
=> feat: inventory service update

src/endpoints/account-members.js, src/endpoints/account-memberships.js, src/types/account-members.d.ts, src/types/account-memberships.d.ts, test/unit/account-memberships.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-9675]filter unassigned account members

.circleci/config.yml
* ### Fix
Fixes a bug
Updated docker image on Circle CI for the release step.
=> fix(build): Updated docker image for the release step

src/endpoints/inventories.js, src/types/inventory.d.ts
* ### Feature
Added ability to delete inventory
=> feat: inventory delete

src/types/order.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: add discount to order

src/endpoints/pcm.js, src/types/pcm.d.ts
* ### Feature
Added endpoint to generate child products
=> feat: generate child products

src/utils/helpers.js
* ### Feature
* ### Refactor
As it was the token validation function would typically fill the users console up with `error` messages. However in many use cases, if `config.reauth` is being used (storefronts etc) this will never realistically be an error state, so we can tidy this up by making it use `config.info` instead
=> feat: error logging

src/types/pcm.d.ts
=> feat: variation matrix type

src/types/catalogs-nodes.d.ts, src/types/catalogs-products.d.ts
* ### Refactor
Updates `NodeBaseResponse` and `ProductResponse ` interfaces, based on API responses got from Postman.
=> refactor: catalog interfaces

src/endpoints/pcm.js, src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add GetChildProducts endpoint

package.json, src/endpoints/files.js, src/factories/request.js, src/types/file.d.ts, yarn.lock
* ### Feature
* ### Refactor
Updates the File.Create method 
- correctly handle file upload by correctly submitting form-data body and headers
- handle new `file_location` option
=> feat: Create file

src/endpoints/pcm-variations.js, src/types/pcm-variations.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Variation modifiers endpoints

src/endpoints/orders.js, src/types/order.d.ts
Feat new feature
* ### Feature
Anonymize order
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> Feat: anonymize order endpoints + types

src/types/catalogs-products.d.ts, src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Product interface

src/types/gateway.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: add stripe_account type

src/endpoints/catalogs.js, src/types/catalogs-rules.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Add CRUD Extend for Rule endpoints

src/endpoints/promotions.js, src/types/promotions.d.ts
* ### Feature
Promotion Version History
Promotion version History Type and endpoint.
* Fixes #
=> feat: Add Promotion version history

src/endpoints/pcm-variations.js, src/endpoints/pcm.js, src/types/core.d.ts, src/types/pcm-variations.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add pagination to options and child products list

src/types/order.d.ts
[## Type](https://elasticpath.atlassian.net/browse/MT-10594)
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: components field added to orders interface

src/types/order.d.ts
* ### Feature
feat: anonymize attribute in order body
Add anonymize attribute type Boolean to order body
* Fixes #
=> feat: anonymize attribute in order body

src/types/pcm.d.ts
* ### Fix
Fixes a bug
Made SKU not required for SKU-less bundle
=> fix: pcm sku type for bundles

src/types/pcm.d.ts
=> fix: made option sku required

src/endpoints/pcm.js, src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add Import products endpoint

src/types/catalogs-products.d.ts, src/types/core.d.ts, src/types/pcm-variations.ts, src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Update QueryableResource interface

src/factories/request.js
https://elasticpath.atlassian.net/browse/MT-10502
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: set credentials to storage only if they are valid

src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add PCM product included interface

src/endpoints/settings.js, src/types/settings.d.ts
https://elasticpath.atlassian.net/browse/MT-3835
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Updatecart endpoint added

src/endpoints/settings.js, src/types/pcm.d.ts, src/types/settings.d.ts
https://elasticpath.atlassian.net/browse/MT-3835
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: cart settings get

src/endpoints/node-relationships.js, src/types/node-relationships.d.ts
* ### Feature
Handle Hierarchies order change
=> feat: node sort order

src/types/price-book-prices.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Fix PriceBookPriceBase interface

src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Add Product Include types

src/config.js, src/factories/request.js, src/types/config.d.ts, test/unit/error.ts
* ### Fix
Fixes a bug
Adds missing retry jitter for retrying 429 requests, which improves retries performance. 
* Fixes #
=> Fix: Adds retry jitter to the retry for 429 requests

src/types/pcm.d.ts
* ### Fix
Fixes a bug
Adds ability to remove sku from the sku field
=> fix: sku type null

package.json, src/config.js, src/factories/secure-cookies-storage.js, src/types/config.d.ts, src/utils/helpers.js, yarn.lock
https://elasticpath.atlassian.net/browse/MT-11481
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: secure cookies

src/endpoints/metrics.js, src/moltin.d.ts, src/moltin.js, src/types/metrics.d.ts, src/utils/helpers.js
https://elasticpath.atlassian.net/browse/MT-10956
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: orders metrics endpoints added

src/endpoints/catalog.js, src/types/catalog.d.ts
* ### Feature
*Adds possibility to pass include parameter to the catalog products endpoint.*
=> feat: include params for catalog products endpoint

src/types/cart.d.ts
Fixes the return type of CreateCart endpoint.
https://github.com/moltin/js-sdk/issues/605
=> fix: fix return type of CreateCart endpoint

src/endpoints/catalog.js, src/types/catalog.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: add new endpoints to shoppers catalog

examples/express-app/yarn.lock
* ### Chore
Regenerate yarn lock
=> chore: update yarn lock

src/endpoints/personal-data.js, src/moltin.d.ts, src/moltin.js, src/types/personal-data.d.ts
* ### Feature
Added support for `/personal-data/logs` endpoint in sdk
=> feat(Endpoint): Added support for PDS

.github/workflows/main.yml
* ### Fix
Fixes branch pipelines skipping checks, by disabling workflow skip on push.
=> [DEVOPS-3298] Disable skipping workflow on push

src/types/catalog.d.ts, src/types/catalogs-products.d.ts, src/types/variations.d.ts
* ### Feature
Provides types declarations that were identified missing during the creation of D2C variations.
Update type declarations.
N/A
N/A
N/A
=> feat: variations and catalog type fixes

src/endpoints/gateways.js, src/types/gateway.d.ts
https://elasticpath.atlassian.net/browse/MT-12093
Adds the onboarding links endpoint to payment gateway. Including types.
N/A
N/A
=> feat(gateway): [MT-12093] onboarding links support.

src/types/order.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Add field to OrderItem response types

src/types/account-address.d.ts, src/types/customer-address.d.ts
* ### Feature
Addresses can now have the attribute region. Region or County or both can be used. 
* Fixes #
=> feat: region as optional field to address

src/types/account-address.d.ts, src/types/customer-address.d.ts
=> Revert "feat: region as optional field to address"

src/endpoints/price-book-price-modifiers.js, src/endpoints/price-books.js, src/moltin.d.ts, src/types/order.d.ts, src/types/price-book-price-modifiers.d.ts, src/types/price-books.d.ts
* ### Feature
As a CM user i should be able to specify my price modifiers inside the create price modifier section
MT-12298
=> feat: price modifiers

src/types/pcm-variations.ts
* ### Fix
Added types for price modifier
=> fix: variation modifier price types

src/endpoints/hierarchies.js, src/types/hierarchies.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Duplicate hierarchy

src/types/settings.d.ts, test/unit/settings.ts
* ### Feature
Added address mandatory fields to settings type definition
* Fixes #
=> feat(Settings): Added Address Mandatory Fields

src/types/config.d.ts
Update types in the send function [MT-12445](https://elasticpath.atlassian.net/browse/MT-12445)
=> fix: Update types in the send function

src/endpoints/catalog.js, src/types/catalog.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add catalog endpoint

src/types/config.d.ts
adding ":" for properties config fetchMaxAttempts
=> fix: add : for properties config fetchMaxAttempts

src/endpoints/pcm-jobs.js, src/endpoints/pcm.js, src/factories/request.js, src/types/pcm-jobs.d.ts, src/types/pcm.d.ts
* ### Feature
Added PCMJobs Endpoint (All, Get, GetJobErrors) under the PCM object in the SDK, alongside the appropriate type declaration file.
* ### Fix
If a falsey version is provided in an endpoint, avoid adding an extra slash character before the next path parameter.
https://elasticpath.atlassian.net/browse/MT-12815
=> feat: add PCM jobs endpoint

src/utils/fetch-polyfill.js
Avoiding importing node-fetch directly
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> refactor(fetch): use cross fetch correctly

src/endpoints/catalog.js, src/types/catalog.d.ts
added missing parameter for endpoint
added correct url template
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: correct GetHierarchyNodes endpoint

src/endpoints/catalog.js, src/types/catalog.d.ts, src/types/catalogs-products.d.ts
Catalog types updated according to Bundles data
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Bundles data added to catalog types

src/endpoints/nodes.js, src/types/nodes.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Add child node pagination

src/config.js
https://elasticpath.atlassian.net/browse/MT-12883
* ### Fix
Fixes a bug that unexpected side-effect is happening when we want to use the in-memory storage
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: storage usage in config updated to omit useless creation

src/types/order.d.ts
* ### Refactor
Adds fields to the order.meta.display_price
* Fixes #
=> refactor(Orders.d.ts): Adds fields to the order.meta.display_price

README.md
Trivial change to trigger release of previous commit: https://github.com/moltin/js-sdk/commit/e492f0569c4ceb76c8f8c97c0b122807711cbd5d
=> feat: Trigger new release

package.json, yarn.lock
cross-fetch is needed at run time and should be part of the regular package dependencies.
* ### Fix
Fixes a bug
=> fix: added cross-fetch to dependencies and removed from devDependencies

src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Add min/max fields in ProductComponents

package.json, rollup.config.js, src/types/account-address.d.ts, yarn.lock
This reverts commit 42da43e835179795a1f8199647c855f348c53f6d.
* ### Chore
Reverting to restore v12 to working major version and then recreating to bump to next major.
=> Revert "chore: reduce public surface of npm package (#675)"

src/endpoints/merchant-realm-mappings.js, src/types/merchant-realm-mappings.d.ts
https://elasticpath.atlassian.net/browse/MT-12872
Adds endpoint for getting merchant-realm-mappings by id
=> feat: adds endpoint for getting merchant-realm-mappings by id

src/types/catalogs-rules.d.ts
Update catalog rules type declaration file to support newer attributes.
[Link to Catalog Rules API Docs](https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/rules/create-a-catalog-rule.html#body)
[Related issue](https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/team/-/issues/38)
=> fix: update catalog rules type declaration file

src/endpoints/erasure-requests.js, src/moltin.d.ts, src/moltin.js, src/types/erasure-requests.d.ts
* ### Feature
Added support for Erasure Requests
=> feat(Erasure Requests): Added support for Erasure Requests

package.json, yarn.lock
* ### Chore
Removing husky as it's 5 years out of date and not used.
=> build: remove unused dep husky

package.json, yarn.lock
* ### Chore
Security version bump
=> build: version bump security

src/types/core.d.ts, src/types/order.d.ts
* ### Fix
Fixes a bug
Order address types. Resolved https://github.com/moltin/js-sdk/issues/615
=> fix: Order address types

playground/index.ts
BREAKING CHANGE: forcing a breaking change release
=> feat!: force a breaking change release

src/endpoints/catalogs.js, src/types/catalog.d.ts, src/types/catalogs-releases.d.ts, src/types/catalogs.d.ts, src/types/order.d.ts
* ### Feature
Add catalog release endpoint. 
* ### Fix
Fix order address types.
=> feat: Add catalog release endpoint

src/endpoints/catalogs.js, src/types/catalogs-releases.d.ts, src/types/catalogs.d.ts
* ### Feature
Delete all catalog releases
* ### Fix
Add pagination to GetAllHierarchies for catalog release endpoint
=> feat: Delete all catalog releases

src/endpoints/transactions.js, src/types/transaction.d.ts
* ### Feature
Adds transaction cancel endpoint and types
=> feat: cancel transaction

README.md
* ### Docs
Update the readme to explain multiple gateway support
=> fix: updated readme with new multiple gateway explainer.

src/types/application-keys.d.ts, test/factories.ts, test/tests.ts, test/unit/application-keys.ts
* ### Test
Adds tests for application keys.
* Fixes #
=> test(application keys): adds tests for application keys endpoint

src/types/application-keys.d.ts
* ### Feature
Adds `Offset` and `Limit` functions to endpoint so Application Keys Endpoint can support pagination.
* Fixes #
=> feat(application keys): adds offset and limit to Application Keys endpoint

.github/workflows/main.yml, package.json, preRelease.sh, yarn.lock
* ### Chore
Trying to hardcode the version on each release so that the SDK version header works as designed
=> chore: write version in prerelease hook

.github/workflows/main.yml
* ### Chore
revert change of #739
=> feat: remove dry-run flag

package.json
* ### Chore
typo - run script correctly
=> chore: correct typo

src/types/catalog.d.ts
https://elasticpath.atlassian.net/browse/MT-13388
Adds a `delta.links.related` to ShopperCatalogReleaseBase interface
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
*Any additional …
=> feat: delta link added to catalog relationship

src/types/pcm.d.ts
* ### Feature
Add external_ref field to PcmProductBase interface
=> feat: Add external_ref field to PcmProductBase

src/types/cart.d.ts
* ### Docs
Correcting broken docs link.
=> docs: correct carts and orders URL

src/types/transaction.d.ts
* ### Feature
*added an optional next_actions property to transactions object that will allow a user to cancel individual transactions in an order
=> feat(transactions): added next_actions property to transactions object 

src/types/cart.d.ts, src/types/order.d.ts, src/types/transaction.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: ConfirmPaymentBody set to have all fields optional

src/endpoints/pcm.js, src/types/pcm-jobs.d.ts, src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Export products

src/types/pcm-jobs.d.ts, src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Update PCM Job interface

src/endpoints/catalogs.js
* ### Feature
Adds pagination support for products and nodes in the PXM Catalogs endpoint
* Fixes [MT-14434]
[MT-14434]: https://elasticpath.atlassian.net/browse/MT-14434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added pagination in products and nodes

src/types/nodes.d.ts
* ### Feature
Add the 'curated_products' attribute field for the node type.
Based on: https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/pim.svc/-/issues/139
* Fixes #
=> feat: Added curated_products to node type

src/types/order.d.ts
* ### Feature
*Added an optional custom_inputs field to orders*
=> feat(orders): optional custom_inputs field to orders

src/endpoints/catalogs.js, src/types/catalogs-releases.d.ts
* ### Feature
Adds flag for include_organization_resources when releasing catalog.
* Fixes #
=> feat(catalog-releases): adds flag for include_organization_resources

src/types/promotions.d.ts
* ### Feature
added target_attributes to schema type
Closes #777
=> feat: added target_attributes to schema

src/types/catalogs.d.ts, src/types/hierarchies.d.ts, src/types/pcm.d.ts, src/types/price-books.d.ts
* ### Feature
Add owner field in Product, Price Book, Hierarchy, Catalog responses
=> feat: Add owner field

src/endpoints/account-authentication-settings.js, src/types/account-authentication-settings.d.ts, test/unit/account-authentication-settings.ts
* ### Feature
a new API is added for updating account authentication settings
=> [MT-14128] update account auth setttings api

src/types/transaction.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
update details transaction type
* Fixes #
=> fix: Update-details-transaction

src/types/order.d.ts
feat: bundle_configuration to order_item
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
[*A brief description of the goals of the pull request.*](feat: bundle_configuration to order_item)
* Fixes #
=> feat: [MT-150202]Bundle_configuration

src/endpoints/account-memberships.js, src/types/account-memberships.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> [MT-15182] adding account membership api on account member id

src/types/cart.d.ts, src/types/core.d.ts, src/types/order.d.ts
* ### Feature
Implements a new feature 
Added `custom_discounts` property to orders
[MT-15242](https://elasticpath.atlassian.net/browse/MT-15242)
[MT-15242]: https://elasticpath.atlassian.net/browse/MT-15242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added custom_discounts to order

src/types/order.d.ts
* ### Feature
Add formatted value to custom discount orders
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: update formatted type in order CustomDiscount

src/endpoints/subscription-products.js, src/moltin.d.ts, src/moltin.js, src/types/subscription-product.d.ts
* ### Feature
subscriptions product 
subscriptions product CRUD endpoint added
=> feat: subscriptions product

src/types/flow.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Update Flow interface

src/endpoints/gateways.js, src/types/gateway.d.ts
* ### Feature
Adds new Stripe Connect Invoicing endpoints
Adds two new endpoints to get Stripe Connect customers and to send Invoices
Internal CM merge request
=> feat: Add New Stripe Endpoints - Invoices

src/endpoints/application-keys.js
* ### Fix
Fixes a bug
Added override for the Update method in ApplicationKeysEndpoint. This allows users to provide proper `type` value.
=> fix(application keys): fixed issue when updating app keys

src/types/pcm.d.ts
* ### Fix
Added PcmProductAttachmentResponse type to Attach/Detach nodes
* Fixes #
=> fix: Add types to Product Attachment Response

README.md
* ### Docs
Added Retries and Throttling section to README and some minor cleanup to a README file.
=> docs(readme): added Retries and Throttling section to README

src/types/subscription-products.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: subscription product price

src/endpoints/hierarchies.js, src/types/hierarchies.d.ts
* ### Fix
Added Interface for Duplicate hierarchy response
=> fix: Add Interface for Duplicate hierarchy response

src/endpoints/hierarchies.js, src/types/hierarchies.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Duplicate hierarchy interface

src/endpoints/subscription-offerings.js, src/moltin.d.ts, src/moltin.js, src/types/subscription-offerings.d.ts
* ### Feature
Subscription offerings CRUD
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: subscription offerings

src/endpoints/subscription-offerings.js, src/types/subscription-offerings.d.ts, src/types/subscription-products.d.ts
* ### Feature
list offering attachments & build offering
=> feat: list offering attachments & build offering

src/types/nodes.d.ts
* ### Feature
Add sort_order and locales to the NodeBase interface
* Fixes #
=> feat: Add sort_order and locales to the NodeBase interface

src/types/password-profile.d.ts
* ### Fix
Fixes a bug
*updated type for `All` endpoint in password profile to `PasswordProfileListItem`*
=> fix(password profile): Fixed All endpoint for password profile

src/types/password-profile.d.ts
* ### Fix
Fixes a bug
*added export to PasswordProfileListItem*
=> fix(password profile): added export to PasswordProfileListItem

src/types/order.d.ts
fix: add shipping to order meta
=> fix: add shipping to order meta

src/endpoints/subscription-offerings.js, src/types/subscription-offerings.d.ts, src/types/subscription-plans.d.ts, src/types/subscription-products.d.ts
* ### Feature
Added new endpoint to offerings: 
- attach products
- remove product
- attach plans
- remove plan 
* Fixes #
=> feat: offering plans

src/types/promotions.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: consume_unit for promotion codes type

src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Import response

src/endpoints/cart.js, src/types/cart.d.ts, src/types/settings.d.ts
* ### Feature
Cart Custom discount 
* ### Fix
Fixes a bug
* ### Docs
[  Documentation only changes](https://elasticpath.dev/docs/commerce-cloud/carts/custom-discounts/overview)
Add missing endpoints and types for cart custom discount and setting cart
=> feat: cart custom discounts

src/endpoints/settings.js, src/types/settings.d.ts
* ### Feature
subscription settings
Added endpoint for subscription in settings to retrieve `subscription_preview_enabled` 
* Fixes #
=> feat: subscription settings

src/endpoints/account-members.js, src/types/account-members.d.ts
* ### Feature
*Allows you to get account member authentication token using `TokenViaPassword` `TokenViaSelfSignup` `TokenViaOIDC` or `SwitchAccountToken`*
=> feat(account-members): allows account member authentication token

src/endpoints/promotions.js, src/types/promotions.d.ts
* ### Feature
Implements promotion jobs types and endpoint* ### Fix
Add promotion jobs endpoint to get all the jobs, add promotion endpoint, add bulk generation (ASYNC CALL) to the job to create codes.
=> feat: MT-15606 Promotion jobs and bulk generation codes

src/types/pcm-variations.ts
=> Revert "Fix: PcmVariation type"

src/types/pcm-variations.ts
* ### Fix
Updated PcmVariation type to correctly reflect the data returned by the endpoint.
=> feat!: Updated pcm variation type

README.md
Updates the API Reference link to https://elasticpath.dev/docs/commerce-cloud
* ### Docs
* Fixes #
=> docs(readme): update API Reference Link in README

src/endpoints/promotions.js, src/types/promotions.d.ts
* ### Feature
Implements filters on jobs
Support filter on promotions job
* Fixes #
=> feat: jobs filter

src/endpoints/subscriptions.js, src/moltin.d.ts, src/moltin.js, src/types/subscriptions.d.ts
* ### Feature
Implements a new subscription endpoint
* Fixes #
=> feat: subscriptions endpoint

src/types/pcm-variations.ts
* ### Feature
BREAKING CHANGE: Updated the meta.options field of a PcmVariation object to match the object returned by the API. Added PcmVariaitonMetaOption type.
=> feat!: Meta options field of pcm variation type correction

src/types/promotions.d.ts
* ### Feature
auto_add_free_gift
Added an optional field for Bundle_gift schema promotion __> auto_add_free_gift .
=> feat: auto_add_free_gift

src/endpoints/cart.js, src/types/cart.d.ts, src/utils/helpers.js
* ### Feature
Implements a new feature 
*added `CheckoutWithAccountManagementToken` function to cart*
=> feat(cart): added new function to cart

src/endpoints/promotions.js, src/types/promotions.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: get file in promotion export

package.json, test/factories.ts, test/factories/request.ts, test/tests.ts, yarn.lock
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> test: request 401 re auth test

src/endpoints/price-books.js, src/types/price-book-price-modifiers.d.ts, src/types/price-book-prices.d.ts, src/types/price-books.d.ts
* ### Feature
Added new endpoint for Importing product prices and `external_ref` fields to price book and product price interfaces
=> feat: Import product prices endpoint

src/types/cart.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat:snapshot_date for promotion preview

src/types/pcm.d.ts
* ### Feature
Added product_types field to PcmProduct interface
=> feat: Add product types field

.github/workflows/main.yml
* ### Chore
Address node version problem with pipeline
=> chore: update node version for pipeline

src/types/pcm.d.ts
* ### Feature
BREAKING CHANGE: Updated the PcmProductUpdateBody type by adding a partial PcmProductBase type. The new type fixes inaccuracies on the update body's structure. ([Related docs page](https://elasticpath.dev/docs/pxm/products/ep-pxm-products-api/update-a-product#body))
=> feat!: Added partial product base update type

src/types/pcm-variations.ts
=> Revert "feat!: Meta options field of pcm variation type correction"

src/types/pcm-variations.ts
=> Revert "Revert "feat!: Meta options field of pcm variation type correction""

src/endpoints/pcm-jobs.js, src/moltin.d.ts, src/types/pcm-jobs.d.ts
* ### Feature
Added PCMJobs extends CRUDExtend 
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: PCM job endpoint

src/types/hierarchies.d.ts, src/types/pcm-jobs.d.ts, src/types/pcm.d.ts, src/types/product.d.ts
* ### Feature
BREAKING CHANGE:
-  Updated PcmJobBase type
- Updated BuldChildProducts return type
- Updated DuplicateHierarchyJob type
=> feat!: Updated build child products job type. Updated PcmJobBase type

src/types/subscription-products.d.ts
=> Revert "feat: subs product price units"

src/types/subscription-products.d.ts
* ### Feature
subs product price units
* Fixes #
=> fix: subs product price units

src/types/hierarchies.d.ts, src/types/pcm-jobs.d.ts, src/types/pcm.d.ts, src/types/product.d.ts
=> Revert "feat!: Updated build child products job type. Updated PcmJobBase type"

src/types/subscription-products.d.ts
* ### Fix
Make subscription product price units nullable
* Fixes #
=> fix: make price units nullable

src/types/catalogs.d.ts
* ### Fix
Add missed fields to the Catalog Interface
=> fix: Catalog interface

src/types/catalogs-releases.d.ts
* ### Fix
Add an `export_full_delta` field to catalog release body interface
=> fix: Catalog release interface

src/types/application-keys.d.ts
* ### Feature
*adds required `last_used_at` property to application keys*
=> feat(application-keys): adds last_used_at property

src/endpoints/pcm-jobs.js, src/types/pcm-jobs.d.ts
* ### Fix
Pagination support for GetJobErrors endpoint
=> fix: Pagination support for GetJobErrors endpoint

src/types/accounts.d.ts
[MT-17059]feat(accounts): adds external_ref property
[MT-17059]: https://elasticpath.atlassian.net/browse/MT-17059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MT-17059]feat(accounts): adds external_ref property

src/types/order.d.ts
* ### Feature
automatic_payment_methods
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
automatic_payment_methods to order payments ElasticPath Payments by Stripe
* Fixes #
=> feat:automatic_payment_methods to order payments by eP stripe

src/types/pcm.d.ts
* ### Feature
Add Custom Inputs interface
=> feat: Add Custom Inputs interface

src/types/customer.d.ts
* ### Feature
*added optional  `external_ref` property to customer*
=> feat(customer): added optional  external_ref property to customer

src/endpoints/catalogs.js, src/types/catalogs-products.d.ts
* ### Feature
Adds types for breadcrumbs
=> feat: add breadcrumb types

src/types/subscription-plans.d.ts
* ### Feature
Types for subscription plan fixed pricing
* Fixes #
=> feat: plan fixed pricing

.github/workflows/main.yml
* ### Chore
- Updated pipeline node version to 20 for all jobs except test
=> chore: Updated all pipeline jobs' node version to 20 except test job

src/types/pcm-variations.ts
=> Fix: updated sort_order field to include the null value

src/types/rule-promotions.ts, src/types/settings.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: release-promotion builder

src/types/rule-promotions.ts, src/types/settings.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: Promotion builder release

src/types/pcm-variations.ts
=> Revert "Fix: Variation option base type and update body corrections"

src/endpoints/subscription-subscribers.js, src/moltin.d.ts, src/moltin.js, src/types/subscription-subscribers.d.ts
* ### Feature
subscribers endpoint
* Fixes #
=> feat: subscribers endpoint

src/types/subscription-subscribers.d.ts, src/types/subscriptions.d.ts
* ### Feature
Added meta type in subscriber base type,  subscription filter + base type update
* Fixes #
=> feat: meta type to subscriber, subscription filter type

src/types/subscription-offerings.d.ts
* ### Feature
- product type for offering build request
- offering filter interface
* Fixes #
=> feat: product type for offering build request, filter interface

src/endpoints/subscription-jobs.js, src/endpoints/subscription-schedules.js, src/moltin.d.ts, src/moltin.js, src/types/subscription-jobs.d.ts, src/types/subscription-schedules.d.ts
* ### Feature
subscription schedule and job endpoints
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: added subscription schedules and  jobs endpoints

src/types/subscription-plans.d.ts
* ### Feature
Removed billing_day, billing_month_day and status from plans
* Fixes #
=> feat: Removed billing_day, billing_month_day and status from plans

src/types/pcm.d.ts
* ### Feature
Add tags to product interface
* Fixes #
=> feat: Add tags to product interface

src/endpoints/rule-promotions.js, src/types/promotions.d.ts, src/types/rule-promotions.ts
* ### Feature
Promotion Builder code
=> feat: add codes to promotion builder

src/endpoints/settings.js, src/types/settings.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: added update for subscriptions settings

src/types/subscription-offerings.d.ts, src/types/subscription-plans.d.ts, src/types/subscription-products.d.ts, src/types/subscription-schedules.d.ts, src/types/subscription-subscribers.d.ts, src/types/subscriptions.d.ts
* ### Feature
Use timestamps in meta.timestamp instead of attributes in subscriptions
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: subscriptions meta timestamp

src/types/subscription-schedules.d.ts
* ### Feature
Allow null for external reference in schedules
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: Allow null for external reference in schedules

src/endpoints/subscriptions.js, src/types/subscription-offerings.d.ts, src/types/subscriptions.d.ts
* ### Feature
Added GetAttachedPlans and GetAttachedProducts to the subscription endpoint. Added includes to the subscription list.
* Fixes #
=> feat: added GetAttachedPlans and GetAttachedProducts to subs

src/endpoints/subscriptions.js, src/types/subscriptions.d.ts
=> !feat: added CreateState endpoint to subscription, types update

src/types/pcm.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat!: Update product component interface

src/endpoints/custom-apis.js, src/moltin.d.ts, src/moltin.js, src/types/custom-apis.ts
=> feat(custom apis): adds the custom apis endpoint

src/endpoints/subscriptions.js, src/types/subscriptions.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: subscription update endpoint

src/types/account-authentication-settings.d.ts, test/unit/account-authentication-settings.ts
* ### Feature
* ### Fix
Adds a new field account_management_authentication_token_timeout_secs to the account authentication settings object
=> feat: 🎸 configurable token for account management auth settings

src/types/pcm.d.ts
* ### Feature
Add the default type to the component option interface 
* Fixes #
=> feat: Add the default type to the component option interface 

src/endpoints/subscription-dunning-rules.js, src/moltin.d.ts, src/moltin.js, src/types/subscription-dunning-rules.d.ts
* ### Feature
added subscription dunning rules endpoint
* Fixes #
=> feat: added subscription dunning rules endpoint

src/endpoints/subscription-proration-policies.js, src/moltin.d.ts, src/moltin.js, src/types/subscription-proration-policies.d.ts
* ### Feature
Implements a proration policies endpoint
=> feat: subscription proration policies endpoint

src/endpoints/subscription-offerings.js, src/types/subscription-offerings.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat!:  added endpoint to attach proration policy to offerings

src/endpoints/subscription-offerings.js, src/types/subscription-offerings.d.ts
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> feat: added ability to remove attached proration from offering

src/endpoints/subscription-offerings.js, src/types/subscription-offerings.d.ts, src/types/subscription-proration-policies.d.ts
…duct
* ### Feature
* ### Fix
Fixes a bug
* ### Docs
* ### Style
* ### Refactor
* ### Test
* ### Chore
* Fixes #
=> fix: subscription proration policy prefix, offering attach/detach product
