- README.md
- package.json
Package now published under `@moltin` scope. Updating docs to reflect that.
```bash
npm install @moltin/sdk
```
> chore: Use scoped package name

- README.md
- src/factories/request.js
- src/utils/helpers.js
`GET` requests should never have a body value in payloads. Make sure its `undefined` unless specified.
> fix: Set default request body as undefined 

- .eslintrc.yml
- README.md
- src/config.js
- src/endpoints/currencies.js
- src/extends/base.js
- src/factories/request.js
- test/unit/authentication.js
Allow the `host` configuration key to have a custom value assigned during the client instantiation. This is required for enterprise customers using the library.
* Fixes moltin/workflow#2335
> feat: Host config value

- src/factories/request.js
- src/utils/helpers.js
- test/unit/brands.js
- test/unit/categories.js
- test/unit/collections.js
- test/unit/currencies.js
- test/unit/products.js
A `DELETE` request to the API now returns a `204` status with an empty body (as per the JSON API spec). The existing `parseJSON` function was failing as there was no JSON to parse, and the `fetch` library was throwing an exception.
The helper function now checks the status of the response, and resolves accordingly.
> fix: Handle 204 empty API body on DELETE

- package.json
- src/utils/helpers.js
- test/utils/helpers.js
If no IDs are provided to the `buildRelationshipData()` helper function, return an empty array.
> fix: Empty array payload

- README.md
* ✅ Ready
* ### Docs
This fixes the link that was previously pointing to the old v2 docs.
> docs: Fix API reference link in README

- src/endpoints/fields.js
- src/endpoints/flows.js
- src/moltin.js
- test/factories.js
- test/unit/fields.js
- test/unit/flows.js
* ✅ Ready
* ### Feature
Implements CRUD operations for Flows and Flow Entries
Added support for CRUD operations on `/flows` and CRUD operations on `/flows/<slug>/entr[y,ies]`. Requires client credential authentication.
> feat: Added support for CRUD operations with Flows and Flow Entries

- src/factories/request.js
- test/unit/authentication.js
* ✅ Ready
* ### Fix
Fixes an issue where the access token would be cached without reference to a client ID, meaning if the client ID was updated, then the access token would not be refreshed.
This implements a credentials object, which allows us to store the client ID alongside the access token. We check to see if the client ID for the credentials object that we have matches the client ID specified in the config, if not, then we authenticate again.
> fix: Access token cache

- package.json
- rollup/cjs.config.js
- src/utils/helpers.js
- test/utils/helpers.js
- yarn.lock
* ✅ Ready
* ### Fix
Fixes a bug
This fixes a bug that was caused by the `uuid` package and a dependency that was causing issues importing the `umd` bundle. This PR replaces the `uuid` package with `cuid`, which is also a collision resistant package for generating random strings.
I've gone ahead and added a test for the `cartIdentifier` function and also created a separate function that calls the `cuid` package, if we replace this in the future with anything else, we can easily test that `createCartIdentiifer` returns a string.
Also checking the dist still works with I Love Lamp store.
> fix: Replace UUID package

- src/factories/request.js
* ✅ Ready
* ### Fix
Fixes a bug 
* [FIX] Fix `access_token` expiry issue. The length of `Date.now()` int was always greater than the expires value returned from API. This was resulting the `authenicate()` method firing on every request even if there was a valid `access_token` stored
* N/A
* N/A
* N/A
> fix: Fix access_token expiry issue

- package.json
- src/moltin.d.ts
* ✅ Ready
* ### Feature
Adds a TypeScript Declaration File
* Fixes #118
Ideally the base response body for each endpoint would be typed (making sure it allows extending with custom flow fields) but for now each method accepts a generic to allow you to declare the `ResponseBody` on a case by case basis.
If you're not interested in maintaining TS definitions within this repo then I can move it to DefinitelyTyped?
> feat: Add TypeScript typings

- README.md
- src/config.js
- src/endpoints/currencies.js
- src/factories/local-storage.js
- src/factories/memory-storage.js
- src/factories/request.js
- src/moltin.js
- src/utils/helpers.js
- test/tests.js
- test/unit/config.js
- test/utils/helpers.js
* ✅ Ready
* ### Feature
Custom storage strategies
Adds ability to pass in custom `StorageFactory` to make the SDK more suitable for environments which don't have access to `window.localStorage` or `fs`.
I've included a `MemoryStorageFactory` out of the box as it's so simple and I imagine all most Node use-cases require.
#106 #131
> feat: Add ability to use different storage strategies

- src/extends/base.js
- src/factories/request.js
- src/utils/helpers.js
- test/unit/customers.js
- test/unit/orders.js
- test/unit/products.js
* ✅ Ready
* ### Fix
Fixes a bug
Resets `includes`, `sort`, `limit`, `offset`, `filter` properties after request has been made so they don't get sent on subsequent requests
> fix: class inheritance issues

- src/moltin.d.ts
* ✅ Ready
* ### Fix
Fixes a bug
This PR aligns `moltin.d.ts` definitions with actual code.
The products endpoint has the following method:
`AddProduct(productId, quantity = 1, data = {})`
The data parameter wasn't included in TypeScript definitions.
> fix: Update typescript definitions for products endpoint

- src/endpoints/flows.js
- test/unit/flows.js
* ### Feature
Implements a new feature  
* [FEAT] Enabled pagination methods (`Offset()`, `Limit()`) to be chained with `Flows.GetEntries(slug)`.
`Moltin.Flows.Offset(10).Limit(5).GetEntries('blog')`
* N/A
* N/A
* I'd prefer to refactor the entries resource to be its own class, similar to [addresses](https://github.com/moltin/js-sdk/blob/master/src/endpoints/addresses.js) which is also a sub resource. Consider for future improvement (albeit a *breaking change*).
> feat: Flow entries pagination

- package-lock.json
- package.json
- src/config.js
- src/factories/request.js
- src/moltin.d.ts
- test/unit/authentication.js
- test/unit/config.js
* ### Feature
_A brief description of the goals of the pull request._
* Allows `custom_fetch` to be passed into `MoltinGateway` configuration that will be used for authentication calls to API. This allows alternate implementations of the WebAPI Fetch (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) spec to be used.
```
const Moltin = MoltinGateway({
client_id: 'X',
client_secret: 'X',
grant_type: 'client_credentials',
custom_fetch: myCustomWebAPIfetch
})
```
_Other PRs or builds that this PR depends on._
* N/A
* N/A
* Ex. - a scenario where you want to proxy the request for a `client_credentials` token to avoid exposing the `client_secret` in any requests.
> feat: Add custom_fetch to allow alternate WebAPI Fetch implementation

- src/endpoints/products.js
- src/utils/helpers.js
- test/unit/files.ts
Fix
This fixes some unexpected SDK behaviour when following the code example given in the documentation at
https://documentation.elasticpath.com/commerce-cloud/docs/api/catalog/products/relationships/main-image-relationship.html
These docs say to run
Moltin.Products.CreateRelationships(pid, 'main-image', [iid])
but that code fails prior to this commit.
A conditional in `buildRelationshipData` was causing either a single relationship object or an array of such objects to be returned:
| ID \ type | `main-image`  | other        |
| --------- | ------------- | ------------ |
| string    | return object | return array |
| array     | return array  | return array |
The `CreateRelationships`, `DeleteRelationships`, and `UpdateRelationships` endpoints all require a single object rather than
an …
> fix: handle main-image data array

- src/endpoints/cart.js
- src/types/cart.d.ts
- test/unit/cart.ts
* ### Feature
Implements the ability to assign customer id to cart
`POST /v2/carts/:cart_id/relationships/customers` returns `null`
But `nock` didn't allow that, so I used `{}` for the test: https://github.com/moltin/js-sdk/pull/346/files#diff-8452f0531ec683589e7912ada26baf3cR800
> feat: Implements the ability to assign customer id to cart

- src/config.js
- src/endpoints/accounts.js
- src/factories/request.js
- src/moltin.d.ts
- src/moltin.js
- src/types/accounts.d.ts
- src/types/config.d.ts
- test/factories.ts
- test/tests.ts
- test/unit/accounts.ts
- tsconfig.json
* ### Feature
PCM APIs exposed through JS-SDK
Added ability to use PCM APIs by creating alternative auth flow
Code for testing
```
const authenticate = () => {
const body = {
grant_type: 'password',
username: '',
password: '',
client_id: '',
client_secret: ''
}
return fetch('https://api.moltin.com/oauth/access_token', {
method: 'POST',
headers: {
'Content-Type': 'application/x-www-form-urlencoded'
},
body: Object.keys(body)
.map(k => `${encodeURIComponent(k)}=${encodeURIComponent(body[k])}`)
.join('&')
}).then(res => res.json())
}
const Moltin = moltin.gateway({
authenticate
})
Moltin.Authenticate().then(res => console.log(res))
Moltin.Accounts.All().then(({ data }) => console.log(data))
Moltin.Accounts.Keys().then(({ data }) => console.log('Keys',data))
Moltin.Accounts.Stores().then(({ …
```
> feat: expose accounts and store API endpoints

- src/endpoints/customers.js
- src/types/customer.d.ts
- test/unit/cart.ts
- test/unit/customers.ts
* ### Feature
The goal of this feature is to add support for [Proof Key Code Exchange](https://tools.ietf.org/html/rfc7636), and specifically support passing the data back to the back end.
I refactored the code to make it cleaner.
I also add a missing test.
N/A
N/A
N/A
> OIDC PKCE Support

- src/factories/request.js
* ### Refactor
Extension of work already done to expose admin endpoints - adds support for `refresh_token`. We may not need this long term but the current dashboard does make use of it, so adding for completeness.
> refactor: support caching refresh_token in localStorage

- examples/index.html
- package.json
- src/config.js
- src/endpoints/accounts.js
- src/endpoints/cart.js
- src/factories/request.js
- src/moltin.js
- src/types/accounts.d.ts
- src/utils/helpers.js
- test/unit/accounts.ts
- test/utils/helpers.ts
- yarn.lock
* ### Feature
A few things we might need to make use of:
- Expose client side token validation logic so it can be checked in app
- Expose `Me` endpoints explicitly
- Add the ability to disable automatic cart creation on load
- Add the ability to disable automatic re-auth on requests
- Add some missing tests
Will relate to work in https://github.com/moltin/react-dashboard/pull/224
> feat: expose token validation

- src/types/cart.d.ts
* ### Fix
Fixes a bug
Currently, the TypeScript type for `cart` does not match [the docs](https://documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/carts/index.html) and the response from the SDK.
**For example:**
* `cart.meta.display_price.tax` and `cart.meta.display_price.without_tax` are never valid according to the existing type def, but are optional according to the docs.
* `cart.meta.display_price.display_price.tax` is a valid (optional) path under the existing type def. I don't think output is ever expected from the SDK.
_(none)_
There is no open issue for this, but I can open one if needed.
I've made use of your existing `FormattedPrice` interface in this update. It contains all of the correct values and seems to have been made for this purpose. Previously, …
> fix: update cart meta type to reflect SDK response

- src/types/order.d.ts
* ### Fix
Fix for order relationships types
Updated order relationships types to same as in documentation https://documentation.elasticpath.com/commerce-cloud/docs/api/orders-and-customers/orders/index.html#docsNav
Thanks to @yasiloghmani for finding that issue.
> fix: order relationships types

- src/endpoints/cart.js
- src/types/cart.d.ts
- test/unit/cart.ts
* ### Feature
Add the ability to pass a customer token on add promotion requests, to support customer specific promotions
https://elasticpath.atlassian.net/browse/MT-6856
> feat: add support for customer specific promotions

- src/types/pcm.d.ts
Update types in pcmProductBase .
When I UPDATE product with "sku" "Partial-UpdateProduct" as | slug | description | mpn | upc_ean | | null | null | null | null |
>  fix: update types in PCMProductBase

- src/types/core.d.ts
- src/types/order.d.ts
- test/factories.ts
- test/unit/orders.ts
* ### Feature
Include account and account member into the orders
when we call order endpoint with include in query of account or account_member, it should return included items.
`GET /orders/order-1?include=account,account_member`
- https://gitlab.elasticpath.com/commerce-cloud/gateway.svc/-/merge_requests/631
- https://code.elasticpath.com/internal-pd/docs-ep-commerce-cloud/-/merge_requests/449
> [MT-7458] Include account and account member into the orders

- src/endpoints/flows.js
- test/unit/flows.ts
* ### Fix
Fixes a bug
One-to-many relationship is not supported in Flows module, array cannot be passed as body parameter
None
* Fixes https://github.com/moltin/js-sdk/issues/484
None
> fix: Flows One-To-Many relationship is not supported

- src/types/order.d.ts
* ### Feature
As a Dashboard user, I would like to see the line item discounts if there is any item promotions.
Update OrderItem Type in order
As a Dashboard user, I would like to see the line item discounts if there is any item promotions.
https://elasticpath.atlassian.net/browse/MT-8096
> feat: Add discount to OrderItemd Type

- package.json
- src/endpoints/files.js
- src/factories/request.js
- yarn.lock
* ### Fix
Fixes a bug
After discussion with API team: ensure that all file creation requests operate with a FormData object.
This way we can maintain the simple `file_location` creation method by allowing a POJO to be passed without requiring the user to create a `FormData` object of their own (although it doesn't prevent this either)
e.g. `Moltin.Files.Create({ file_location: 'https://file-url.com })`
> fix: use formdata for all file creation requests

- src/types/address.d.ts
- test/unit/authentication-realm.ts
* ### Fix
Fixes a bug
This PR is re-introducing `address.d.ts` file that combines `AccountAddress` and `CustomerAddress` using TypeScript's discriminated union. In addition some tests have been fixed.
> fix(types): Unified Customer add Account addresses

- src/config.js
- src/factories/request.js
- src/types/config.d.ts
- test/unit/error.ts
Adds `retryJitter` parameter to the sdk that defaults to 0.5 a second (or 500 milliseconds). When performing a retry a value between 0 to .5 seconds will be added to the retry value to create a jitter. This helps decorrolate and smooth out traffic over time.
> performance: Adds retry jitter to the retry for 429 requests

- src/config.js
- src/factories/request.js
- src/types/config.d.ts
- test/unit/error.ts
Reverts moltin/js-sdk#593
Will reopen a PR with `fix:` to ensure it gets added as a patch releaes.
> Revert "performance: Adds retry jitter to the retry for 429 requests"

- src/types/catalog.d.ts
'component_products' can be used as an include parameter on the catalog products endpoint, but the sdk hasn't supported it yet.
* ### Feature
> feat: add new option to catalog products include

- .github/workflows/main.yml
* ### Fix
Fixes a bug
Existing CI configuration uploads artifacts into npmjs with incorrect folder structure. When github action downloads artifacts from build job, it automatically flattens the file structure. This PR adds configuration to maintain the file structure so that npmjs artifact contains `dist` directory.
> [DEVOPS-3298] ci: fix npm release issue due to github action misconfiguration

- src/endpoints/data-entry.js
- src/moltin.d.ts
- src/moltin.js
- src/types/data-entries.d.ts
* ### Feature
Added support for DataEntries endpoint
This PR adds types and functions for `/personal-data/related-data-entries` api. This complements functionality that was added for the `/personal-data/logs` api.
> feat(New endpoint): Added support for DataEntries endpoint

- src/types/config.d.ts
* ### Fix
This redefines GrantType as a `const enum` which fixes 'Cannot read properties of undefined` error.
> fix(Types): Redefined GrantType as a const enum

- src/config.js
- src/factories/request.js
- src/types/config.d.ts
- test/unit/error.ts
Allows the number of retries when getting status 429 to be configured. The default is 4.
* ### Feature
* Fixes #
> feat(Config): Add RetryMaxAttempts to config

- package.json
- src/utils/helpers.js
- test/utils/helpers.ts
- yarn.lock
* ### Fix
Fixing an exception that happens when response body contains non-empty non-json string. Before this we were special casing empty strings, but non-empty strings that cannot be parsed to json were causing an error.
> fix: Fixed crashing on non-json response

- src/types/catalogs-products.d.ts
* ### Fix
Fix to make `component_products` field optional in `product.meta` object
> fix: component_products field in product.meta should be optional

- src/endpoints/catalog.js
* ### Fix
Fixes a bug
The call to shopperCatalog.Get() method without any options would throw referenceError.Also, Current implementation is making API call to an invalid endpoint('https://api.moltin.com/v2/catalog').
1. Calling Catalog.Get() without customer token
2. Calling API to invalid api endpoint
* Fixes #
1. Add default argument to the method definition (ShopperCatalog.Get().
2. Update config.version in ShopperCatalogClass constructor.
> Fix issue while calling ShopperCatalog.Get() method.

- package.json
- rollup.config.js
- src/types/account-address.d.ts
- yarn.lock
* ### Chore
Reduce public surface of npm package
Bundle pushed to the npm registry less cluttered with playground, examples and src folders that don't need to be there.
Updated the build output to include a rolled up version of .d.ts files.
Should be no changes for consumers.
- Updated the build output to include a rolled up version of .d.ts files.
- Changed the package.json files array to include only the files we want to be present in the bundle
- package.json README and LICENSE are [included by default](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files)
> chore: reduce public surface of npm package

- src/types/catalogs-releases.d.ts
- src/types/hierarchies.d.ts
* ### Feature
adding types for GetAllHierarchies from catalog releases
> fix: missing types for GetAllHierarchies

- src/endpoints/pcm.js
- src/types/pcm.d.ts
Couldn't resolve conflicts for https://github.com/moltin/js-sdk/pull/558 so created a new pr and reduced the scope.
https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/products/relationships/get-a-products-nodes.html
* ### Feature
* ### Refactor
* Updates on Catalogs Nodes, Products and Releases interfaces.
* PCM endpoint `GetNodesByProduct` referencing `Get a product's nodes` Postman endpoint.
> feat: added request for get products nodes

- src/types/catalog.d.ts
* ### Fix
Fixes a bug
Should return Node instead of Hierarchy
> fix: correct GetHierarchyNodes return type

- src/factories/request.js
- src/moltin.d.ts
- src/moltin.js
- src/types/catalog.d.ts
- src/utils/helpers.js
- test/unit/promotions.ts
- test/unit/variations.ts
* ### Fix
Fixes a bug
BREAKING CHANGE:
Removed client_id from `moltinCredentials` credentials data in local storage. Use `Moltin.config.clientId` instead
Updated the response type of `Moltin.credentials` to properly reflect that it can return `null` if the localstorage entry has not yet been created e.g. unauthenticated.
Updated return type of GetHierarchyNodes method
> fix!: credentials

- src/types/pcm.d.ts
It was using the default typescript node type
* ### Fix
Fixes a bug
Types were using the default typescript node type instead of our epcc node type
> fix: import correct node version

- src/types/catalogs-products.d.ts
[## Type](https://elasticpath.atlassian.net/browse/MT-13264)
`original_display_price` is required to handle the previous price in Products response.
> feat: original_display_price field added to ProductResponse interface

- src/endpoints/cart.js
- src/types/cart.d.ts
* ### Feature
added include items and tax_items for cart endpoint 
- [include docs tax items](https://documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-orders/carts/cart-items/get-cart-items.html#query-parameters) 
- [include docs items](https://documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-orders/carts/get-a-cart.html#query-parameters)
> feat: added include items and tax_items for cart endpoint

- src/types/cart.d.ts
- test/unit/cart.ts
* ### Feature
Tax items now have a required `type` property as it's required by the api when creating a tax item. I've also added a response version of the object to reflect that the id is present.
> feat: added tax item includes and items includes types.

- src/endpoints/orders.js
* ### Fix
Fixes a bug
buildRequestBody checks for an options property and if it's present expects a props to be on a data property. This is not the case with payment requests.
When an options property is present on a payment request the data field in the request becomes undefined. e.g. { data: undefined, options: {...} }
Manual wrapping and then telling the request to not wrap the data prevents this.
> fix: do manual wrapping of body

- src/types/order.d.ts
- src/types/util.d.ts
* ### Feature
BREAKING CHANGE: Types for data being passed to gateway.Order.Payment have been constrained further to help make it more clear what options are required by which payment gateway in the devs IDE.
Each payment type is now part of a discriminated union the key property being `gateway`. This pass was done using the current documentation as the source of truth if anything is missing let us know.
> feat!: Constrained types for Payment endpoint.

- src/endpoints/application-keys.js
- src/moltin.d.ts
- src/moltin.js
- src/types/application-keys.d.ts
* ### Feature
Adds application keys endpoint to the SDK. This endpoint allows creation of store keys that can be utilized by any user in the store and it not tied to a user. 
`client_secret` is optional param as it is only visble on creation, GET calls should not return `client_secret`
> feat(application keys): adds Application Keys endpoint

- src/endpoints/catalog.js
- src/endpoints/catalogs.js
- src/types/catalog.d.ts
- src/types/catalogs-products.d.ts
* ### Feature
add /children/ endpoint in catalog view
ShopperCatalog: `moltin.ShopperCatalog.Products.GetProductChildren({productId})`
Catalogs: `moltin.Catalogs.Products.GetCatalogProductChildren({catalogId, releaseId, productId})`
> feat: catalog product children

- src/types/order.d.ts
BREAKING CHANGE: the payment body is different
* ### Feature
*Elastic Path Payments Stripe takes in “payment_method_types” field instead of “payment” field*
> feat(orders): update payment to payment_method_types

- src/endpoints/catalogs.js
- src/types/catalogs-products.d.ts
* ### Feature
This PR is adding support for fetching all products from a catalog release
https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/releases/products/get-all-products-in-a-release.html
> Added support for getting products by release

- src/types/order.d.ts
- test/unit/orders.ts
We need to call the `Cconfirm` endpoint to confirm the EP Stripe payment.
The "Confirm" endpoint was described with the wrong `body`. After some investigations, I assume that body should be { data: {} }
Links with described flow:
https://elasticpath-software.slack.com/archives/C03L8QEUG5A/p1661810465608449?thread_ts=1661552938.535809&cid=C03L8QEUG5A
https://elasticpath-software.slack.com/archives/G0193Q8HNFJ/p1661966012599799?thread_ts=1661957241.000449&cid=G0193Q8HNFJ
> fix: Confirm endpoint body changed to which is in docs

- src/types/transaction.d.ts
* ### Feature
*added an optional next_actions property to transactions object that will allow a user to cancel individual transactions in an order*
> feat(transactions): added next_actions property to transactions object

- src/endpoints/pcm.js
- src/types/pcm.d.ts
* ### Feature
feat: hierarchy attach/detach nodes
This allows you to pass in a filter from the product list screen and use whatever the products are returned for node assignment.
> feat: hierarchy attach/detach nodes

- src/endpoints/catalogs.js
* ### Feature
Added pagination for GetProductsInCatalogRelease() method. This allows users to chain it like:
```
const products = await gateway.Catalogs.Products
.Offset(x)
.Limit(y)
.GetProductsInCatalogRelease({});
```
> Added pagination for GetProductsInCatalogRelease()

- src/types/order.d.ts
https://elasticpath.atlassian.net/browse/MT-14072
`ManualPayment` interface updated:
- removed extending from `PaymentBase` interface as long as `payment` field is excessive
> fix: 'payment' removed from ManualPayment interface

- src/utils/helpers.js
- test/utils/helpers.ts
* ### Fix
Fix logic to add support for 'in' operator in filters
The current logic for creating query parameters for Elastic Path filters doesn't work with the 'in' operator.
`const filter = {
"in": {
"sku":  ["prod123", "prod456"]
}
}
`
If the above filter variable is passed to the existing `formatFilterString()` function implementation, it returns an invalid output like `in(sku.0,prod123,sku.1,prod456)`.
This fix supports processing an array of values, resulting in the following output.
`in(sku, "prod123","prod456")`
`Sample url: https://api.moltin.com/pcm/products?page[limit]=25&filter=in(sku,prod123,prod456)`
> feat(Filters):  add support for 'in' operator in ElasticPath filter

- src/types/catalogs.d.ts
* ### Feature
Added pricebook_ids to catalogs base type. Made that and the pricebook_id property optional, as they can either be included, but never both or neither of them.
See documentation for more info on the pricebook_ids and pricebook_id fields: https://documentation.elasticpath.com/commerce-cloud/docs/api/pcm/catalogs/configure/create-a-catalog.html#body
* Part of this ticket: https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/121
> feat: added pricebook_ids field to catalogs base type

- src/endpoints/cart.js
- src/types/cart.d.ts
* ### Fix
**Added optional header parameter to addProduct function in cart module**  
As of now, currency is set at gateway level during Motlin gateway initialization. If the gateway is initialized based on a singleton pattern, it's difficult to reuse the same gateway across multiple apis from a storefront that handles multiple currencies. One solution would be to use a request scoped gateway initialization which is an expensive approach as the number of requests gets higher. An alternative way is to pass currencies as optional parameters with addProduct or similar APIS which makes it more flexible to use.
N/A
##Issue Link
https://github.com/moltin/js-sdk/issues/769
> feat: Add optional header parameter to the addProduct function in cart module

- src/types/promotions.d.ts
* ### Feature
*Added `target_conditions` and updated `exclude` in promotions schema*
Both `target_conditions` and `exclude` were updated in the following promotions:
* [Item Fixed Discount](https://documentation.elasticpath.com/commerce-cloud/docs/changelog.html#february-16-2023:~:text=Create%20Item%20Fixed%20Discount%20Promotion%20for%20items)
* [Item Percent Discount](https://documentation.elasticpath.com/commerce-cloud/docs/changelog.html#february-16-2023:~:text=Promotion%20for%20items-,Create%20Item%20Percent%20Discount%20Promotions,-Create%20X%20for)
* [X for Y Discount](https://documentation.elasticpath.com/commerce-cloud/docs/changelog.html#february-16-2023:~:text=Percent%20Discount%20Promotions-,Create%20X%20for%20Y%20Discount%20Promotion,-Create%20X%20for) …
> feat(promotions): added target_conditions to promotions

- src/endpoints/catalogs.js
- src/types/catalogs-nodes.d.ts
- src/types/catalogs-products.d.ts
- src/types/node-relationships.d.ts
* ### Feature
Gitlab issue:[ CM: Allow users to curate a node's products](https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/90)
- Addition of the 'curated_product' optional boolean field for node products
- Addition of 'curated_products' optional string array for catalogs nodes
> feat: Update node product and catalog node types

- src/types/nodes.d.ts
* ### Fix
Fixes a bug
**This MR is part of the work required for the 'CM: Curated Node Products' ticket**
- Updated the Hierarchies.Nodes.Update({hiearchyId, nodeId, body}) 'body' type to be more accurate.
The 'type' and 'id' fields are required in the request body but the 'attributes' object's properties are optional. The 'relationships' object is irrelevant in the node update request body.
Docs: https://elasticpath.dev/docs/pxm-hierarchies/nodes-api/update-a-hierarchy-node#body
> fix: Update Node request body type

- src/endpoints/catalog.js
- src/types/catalog.d.ts
- src/types/file.d.ts
This enables implicit token users to get pricing and configuration for selected component options.
e.g. /catalog/products/14edd744-c615-4a33-a2c2-df999bbb5103/configure
example use:
```
gateway.ShopperCatalog.Products.Configure({
productId: '14edd744-c615-4a33-a2c2-df999bbb5103',
selectedOptions: {
plants: {
'a158ffa0-5d16-4325-8dcc-be8acd55eecf': 1
},
pots: {
'fc520b37-a709-4032-99b3-8d4ecc990027': 1
},
tools: {
'1cc7f871-1071-4908-a79d-633adc56044a': 1,
'7ffe107d-c5bd-4de4-b8f0-a58d90cb3cd3': 1
}
}
})
```
e.g. in(id,4b97cee1-70ea-4d97-8d46-9c441c3317de,2b435629-28d3-4555-9ce1-204a2f72b412)
example use:
```
gateway.Files.Filter({
in: {
id: [
'4b97cee1-70ea-4d97-8d46-9c441c3317de',
'2b435629-28d3-4555-9ce1-204a2f72b412'
]
}
}).All()
```
> feat: added support for configure and in filter

- src/types/catalog.d.ts
add missing return type for shopper product configure endpoint
Previously was untyped and returning `any`, should be returning `Promise<ShopperCatalogResource<ProductResponse>>`
> fix: add missing return type for shopper product configure endpoint

- src/endpoints/hierarchies.js
- src/types/hierarchies.d.ts
* ### Fix
Update Duplicate Hierarchy endpoint to `/hierarchies/:hierarchyId/duplicate_job`.
Added `attributes.include_products` field in the Body of the request.
> fix: Duplicate Hierarchy endpoint

- src/types/pcm.d.ts
* ### Feature
Added 'build_rules' field to Pcm product. 
See docs for more details: 
- https://elasticpath.dev/docs/pxm/products/ep-pxm-products-api/pxm-products-api-overview#the-build_rules-object
- https://elasticpath.dev/docs/pxm/products/pxm-product-variations/build-pxm-variations
This is related to tickets [#191](https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/191) and [#175](https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/175)
> Feat: Added build_rules field to pcm product

- src/types/customer.d.ts
* ### Fix
Fixes a bug
as per the [docs](https://elasticpath.dev/docs/commerce-cloud/customer-management/customer-managment-api/get-all-customers#filtering) the following fields are missing from the CustomerFilter type
> fix: add missing customer filter properties

- src/types/pcm-variations.ts
* ### Fix
Updated `PcmVariation` type to correctly reflect the data returned by the endpoint. [Go to change](https://github.com/moltin/js-sdk/compare/fix/pcm-variation-option-types?expand=1#diff-13e3d4a04782e0d98ab8cc460aaf25038e1278ee73793b7a2f2768e1c7f1fb57R24)
All other changes are format fixes.
> Fix: PcmVariation type

- src/types/pcm-variations.ts
…e-organisation support variations
* ### Fix
BREAKING CHANGE: Turn variation meta field into optional to support pre-organization variations
> !feat: Optional variation meta field 

- src/endpoints/catalog.js
- src/types/catalog.d.ts
* ### Feature
Adding a With function to catalog node products request
- there was no direct way to pass in include header without using additionalHeaders
N/A
N/A
N/A
> feat: adding a With function to catalog node products request

- src/endpoints/catalogs.js
- src/types/catalogs-products.d.ts
* ### Feature
BREAKING CHANGE: Added moltin instance to GetCatalogProducts method so that the filter and other query params are not retained between calls on the same endpoint. Updated filter types for the same endpoint. Mark "GetProductsInCatalogRelease" as deprecated since it has the same functionality as the aforementioned method.
Pushed a commit where I removed methods that call these non-existent endpoints:
- `catalogs/products/${productId}`
- `catalogs/nodes/${nodeId}/relationships/products`
- `catalogs/products`
Also added:
- GetCatalogReleaseHierarchyProducts
- GetCatalogReleaseProductChildren
Renamed the methods within the Catalogs.Products class and fixed the relevant types.
> feat!: Added instance within GetCatalogProducts method & type fixes 

- src/types/pcm-variations.ts
* ### Feature
- Add 'sort_order' field to variation and variation option interfaces.
Related issue: https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/280
> Feat: Add sort_order to variation and variation option interfaces

- src/types/pcm-variations.ts
* ### Feature
BREAKING CHANGES:
- Fix base types for variation and variation options
- Update body is different from respective base when it comes to the `sort_order` field. It can include the null value
- Variation option response type was corrected
> Feat!: Corrected variation and variation option response and update body types

- src/types/pcm-variations.ts
…e body type for variation and variation option
* ### Fix
- PCMVariationOptionBase - removed 'type' field and added it to PCMVariationOption type
- Fixed UpdateBody types for Variation and Variation Option to properly add the null | number | undefined type to the sort_order field
> Fix: Variation option base type and update body corrections

- src/types/pcm-variations.ts
* ### Fix
Original PR: #911 
- PCMVariationOptionBase - removed 'type' field and added it to PCMVariationOption type
- Fixed UpdateBody types for Variation and Variation Option to properly add the null | number | undefined type to the sort_order field
> fix: Variation & variation option update body type

- src/endpoints/pcm.js
- src/types/pcm.d.ts
- src/utils/helpers.js
* ### Feature
- Updated `PCM.ExportProducts` method with a second optional boolean argument for the value of the `useTemplateSlugs` query param
- `buildURL` and `buildQueryParams` helper functions have been updated to accept  and append the `useTemplateSlugs` param to the final URL
Relevant Issue: https://gitlab.elasticpath.com/commerce-cloud/ncl-projects/paragon/team/-/issues/283
> feat: Added useTemplateSlugs query param as optional argument to PCM.ExportProducts method

- src/endpoints/custom-apis.js
- src/types/custom-apis.ts
BREAKING CHANGE: changed the endpoint in entries and it now uses customApiId instead of customApiSlug
* ### Refactor
*Changed the endpoint in entries and it now uses `customApiId` instead of `customApiSlug`*
> refactor(custom apis): updated entries to use id instead of slug
